# Generated by Django 5.2.6 on 2025-09-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novels',
            name='is_toptrend',
        ),
        migrations.RemoveField(
            model_name='novels',
            name='is_trending',
        ),
    ]
